version: "3.9"

x-common-data: &common-data
  environment:
    spring.redis.host: view-redis-cache

services:
  view-redis-cache:
    container_name: view-redis-cache
    image: redis

  view-api:
    <<: *common-data
    container_name: view-api
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - view-redis-cache
